// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\pch\pch.h
// DESCRIPTION: En-tête précompilé pour la compilation
// AUTEUR: Rihen
// DATE: 2026
// -----------------------------------------------------------------------------

#pragma once

// Ajoutez ici les en-têtes rarement modifiés
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <memory>
#include <vector>
#include <string>
#include <functional>
#include <utility>
#include <type_traits>
#include <cassert>

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================