// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\FileSystem\NkPath.h
// DESCRIPTION: Path manipulation and utilities
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_FILESYSTEM_NKPATH_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_FILESYSTEM_NKPATH_H_INCLUDED

#include "NKCore/NkTypes.h"
#include "NKContainers/String/NkString.h"
#include "NKContainers/Sequential/NkVector.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief Path manipulation class
         * 
         * Gère les chemins de fichiers de manière cross-platform.
         * Supporte Windows (C:\path\file.txt) et Unix (/path/file.txt).
         * 
         * @example
         * NkPath path("C:/Users/Documents/file.txt");
         * NkString dir = path.GetDirectory();     // "C:/Users/Documents"
         * NkString file = path.GetFileName();     // "file.txt"
         * NkString ext = path.GetExtension();     // ".txt"
         */
        class NkPath {
        private:
            NkString mPath;
            
            static constexpr char PREFERRED_SEPARATOR = '/';
            static constexpr char WINDOWS_SEPARATOR = '\\';
            
            void NormalizeSeparators();
            
        public:
            // Constructors
            NkPath();
            NkPath(const char* path);
            NkPath(const NkString& path);
            NkPath(const NkPath& other);
            
            // Assignment
            NkPath& operator=(const NkPath& other);
            NkPath& operator=(const char* path);
            
            // Path operations
            NkPath& Append(const char* component);
            NkPath& Append(const NkPath& other);
            NkPath operator/(const char* component) const;
            NkPath operator/(const NkPath& other) const;
            
            // Path components
            NkString GetDirectory() const;
            NkString GetFileName() const;
            NkString GetFileNameWithoutExtension() const;
            NkString GetExtension() const;
            NkString GetRoot() const;
            
            // Path properties
            bool IsAbsolute() const;
            bool IsRelative() const;
            bool HasExtension() const;
            bool HasFileName() const;
            
            // Path modification
            NkPath& ReplaceExtension(const char* newExt);
            NkPath& ReplaceFileName(const char* newName);
            NkPath& RemoveFileName();
            NkPath GetParent() const;
            
            // Conversion
            const char* CStr() const;
            NkString ToString() const;
            NkString ToNative() const;  // With platform-specific separators
            
            // Comparison
            bool operator==(const NkPath& other) const;
            bool operator!=(const NkPath& other) const;
            
            // Static helpers
            static NkPath GetCurrentDirectory();
            static NkPath GetTempDirectory();
            static NkPath Combine(const char* path1, const char* path2);
            static bool IsValidPath(const char* path);
        };
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_FILESYSTEM_NKPATH_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================
