# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Nkentseu_config = debug_x64
  Unitest_config = debug_x64
  Nova_config = debug_x64

else ifeq ($(config),release_x64)
  Nkentseu_config = release_x64
  Unitest_config = release_x64
  Nova_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Nkentseu Unitest Nova

.PHONY: all clean help $(PROJECTS) Core Engine

all: $(PROJECTS)

Core: Nkentseu Unitest

Engine: Nova

Nkentseu:
ifneq (,$(Nkentseu_config))
	@echo "==== Building Nkentseu ($(Nkentseu_config)) ===="
	@${MAKE} --no-print-directory -C Core/Nkentseu -f Makefile config=$(Nkentseu_config)
endif

Unitest: Nkentseu
ifneq (,$(Unitest_config))
	@echo "==== Building Unitest ($(Unitest_config)) ===="
	@${MAKE} --no-print-directory -C Core/Unitest -f Makefile config=$(Unitest_config)
endif

Nova: Nkentseu Unitest
ifneq (,$(Nova_config))
	@echo "==== Building Nova ($(Nova_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Nova -f Makefile config=$(Nova_config)
endif

clean:
	@${MAKE} --no-print-directory -C Core/Nkentseu -f Makefile clean
	@${MAKE} --no-print-directory -C Core/Unitest -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/Nova -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Nkentseu"
	@echo "   Unitest"
	@echo "   Nova"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"