// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\Assert\NkAssert.cpp
// DESCRIPTION: Implémentation gestionnaire assertions
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#include "NkAssert.h"
#include <cstdio>
#include <cstdlib>

/**
 * @brief Namespace nkentseu.
 */
namespace nkentseu {
	/**
	 * @brief Namespace core.
	 */
	namespace core {

		static NkAssertCallback sAssertCallback = &NkAssertHandler::DefaultCallback;

		NkAssertCallback NkAssertHandler::GetCallback() {
			return sAssertCallback;
		}

		void NkAssertHandler::SetCallback(NkAssertCallback callback) {
			sAssertCallback = callback ? callback : &DefaultCallback;
		}

		NkAssertAction NkAssertHandler::DefaultCallback(const NkAssertionInfo &info) {
			// Afficher l'assertion échouée
			fprintf(stderr, "\n=== ASSERTION FAILED ===\n");
			fprintf(stderr, "Expression: %s\n", info.expression);
			if (info.message && info.message[0]) {
				fprintf(stderr, "Message: %s\n", info.message);
			}
			fprintf(stderr, "File: %s:%d\n", info.file, info.line);
			fprintf(stderr, "Function: %s\n", info.function);
			fprintf(stderr, "========================\n\n");

		#if defined(NK_DEBUG)
			return NkAssertAction::NK_BREAK;
		#else
			return NkAssertAction::NK_ABORT;
		#endif
		}

		NkAssertAction NkAssertHandler::HandleAssertion(const NkAssertionInfo &info) {
			return sAssertCallback(info);
		}

	} // namespace core
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================