// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Serialization\JSON\NkJSONWriter.h
// DESCRIPTION: Déclaration de Sérialisation de données
// AUTEUR: Rihen
// DATE: 2026
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_SERIALIZATION_JSON_NKJSONWRITER_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_SERIALIZATION_JSON_NKJSONWRITER_H_INCLUDED

namespace nkentseu {
    namespace entseu {
        // TODO: Ajouter les déclarations ici
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_SERIALIZATION_JSON_NKJSONWRITER_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================