// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkClock.h
// DESCRIPTION: High-precision clock
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#include "NKCore/NkTypes.h"
#include "NkDuration.h"

namespace nkentseu {
    
    /**
     * @brief High-precision clock
     * 
     * Fournit un accès à l'horloge système haute résolution.
     * Utilise std::chrono::high_resolution_clock ou équivalent système.
     * 
     * @example
     * auto start = NkClock::Now();
     * // ... do work ...
     * auto end = NkClock::Now();
     * auto elapsed = end - start;
     * printf("Took: %s\n", elapsed.ToString().CStr());
     */
    class NkClock {
        public:
            /**
             * @brief Time point from clock
             */
            struct TimePoint {
                core::int64 Nanoseconds;
                
                TimePoint() : Nanoseconds(0) {}
                explicit TimePoint(core::int64 ns) : Nanoseconds(ns) {}
                
                NkDuration operator-(const TimePoint& other) const {
                    return NkDuration::FromNanoseconds(Nanoseconds - other.Nanoseconds);
                }
                
                TimePoint operator+(const NkDuration& duration) const {
                    return TimePoint(Nanoseconds + duration.ToNanoseconds());
                }
                
                TimePoint operator-(const NkDuration& duration) const {
                    return TimePoint(Nanoseconds - duration.ToNanoseconds());
                }
                
                bool operator==(const TimePoint& other) const {
                    return Nanoseconds == other.Nanoseconds;
                }
                
                bool operator!=(const TimePoint& other) const {
                    return Nanoseconds != other.Nanoseconds;
                }
                
                bool operator<(const TimePoint& other) const {
                    return Nanoseconds < other.Nanoseconds;
                }
                
                bool operator<=(const TimePoint& other) const {
                    return Nanoseconds <= other.Nanoseconds;
                }
                
                bool operator>(const TimePoint& other) const {
                    return Nanoseconds > other.Nanoseconds;
                }
                
                bool operator>=(const TimePoint& other) const {
                    return Nanoseconds >= other.Nanoseconds;
                }
            };
            
            // Get current time
            static TimePoint Now();
            
            // Get elapsed time since program start
            static NkDuration GetElapsedTime();
            
            // Sleep functions
            static void Sleep(const NkDuration& duration);
            static void Sleep(core::int64 milliseconds);     // convenience: ms as integer
            static void Sleep(float64 milliseconds); // convenience: ms as float
            static void SleepMilliseconds(core::int64 milliseconds);
            static void SleepMicroseconds(core::int64 microseconds);

            // Yield the current thread's time-slice to the OS scheduler
            static void YieldThread();

            // Utility
            static core::int64 GetFrequency();  // Clock frequency in Hz
            
        private:
            static TimePoint sStartTime;
            static void InitializeStartTime();
    };
        
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================