// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkClock.cpp
// DESCRIPTION: High-precision clock implementation
// AUTEUR: Rihen
// DATE: 2026-02-10
// -----------------------------------------------------------------------------

#include "NkClock.h"

#ifdef _WIN32
    #include <windows.h>
#else
    #include <time.h>
    #include <unistd.h>
    #include <sched.h>
#endif

namespace nkentseu {
        
    NkClock::TimePoint NkClock::sStartTime;
    
    void NkClock::InitializeStartTime() {
        static bool initialized = false;
        if (!initialized) {
            sStartTime = Now();
            initialized = true;
        }
    }
    
    NkClock::TimePoint NkClock::Now() {
        #ifdef _WIN32
        static LARGE_INTEGER frequency = {0};
        if (frequency.QuadPart == 0) {
            QueryPerformanceFrequency(&frequency);
        }
        
        LARGE_INTEGER counter;
        QueryPerformanceCounter(&counter);
        
        // Convert to nanoseconds
        core::int64 nanoseconds = (counter.QuadPart * 1000000000LL) / frequency.QuadPart;
        return TimePoint(nanoseconds);
        
        #else
        struct timespec ts;
        clock_gettime(CLOCK_MONOTONIC, &ts);
        
        core::int64 nanoseconds = static_cast<core::int64>(ts.tv_sec) * 1000000000LL + ts.tv_nsec;
        return TimePoint(nanoseconds);
        #endif
    }
    
    NkDuration NkClock::GetElapsedTime() {
        InitializeStartTime();
        return Now() - sStartTime;
    }
    
    void NkClock::Sleep(const NkDuration& duration) {
        #ifdef _WIN32
        ::Sleep(static_cast<DWORD>(duration.ToMilliseconds()));
        #else
        core::int64 microseconds = duration.ToMicroseconds();
        usleep(static_cast<useconds_t>(microseconds));
        #endif
    }
    
    void NkClock::Sleep(core::int64 milliseconds) {
        Sleep(NkDuration::FromMilliseconds(milliseconds));
    }

    void NkClock::Sleep(float64 milliseconds) {
        Sleep(NkDuration::FromMilliseconds(milliseconds));
    }

    void NkClock::SleepMilliseconds(core::int64 milliseconds) {
        Sleep(NkDuration::FromMilliseconds(milliseconds));
    }

    void NkClock::SleepMicroseconds(core::int64 microseconds) {
        Sleep(NkDuration::FromMicroseconds(microseconds));
    }

    void NkClock::YieldThread() {
        #ifdef _WIN32
        ::SwitchToThread();
        #else
        ::sched_yield();
        #endif
    }

    core::int64 NkClock::GetFrequency() {
        #ifdef _WIN32
        LARGE_INTEGER frequency;
        QueryPerformanceFrequency(&frequency);
        return frequency.QuadPart;
        #else
        return 1000000000LL;  // 1 GHz (nanosecond resolution)
        #endif
    }
        
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================