// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkDuration.h
// DESCRIPTION: Duration representation and manipulation
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#include "NKCore/NkTypes.h"
#include <string>

namespace nkentseu {
    
    /**
     * @brief Duration class for time intervals
     * 
     * Représente une durée de temps avec précision nanoseconde.
     * Supporte conversion entre différentes unités.
     * 
     * @example
     * NkDuration dur = NkDuration::FromSeconds(2.5);
     * core::float64 ms = dur.ToMilliseconds();  // 2500.0
     * core::float64 us = dur.ToMicroseconds();  // 2500000.0
     */
    class NkDuration {
        private:
            core::int64 mNanoseconds;  // Internal storage in nanoseconds
            
        public:
            // Constructors
            NkDuration();
            explicit NkDuration(core::int64 nanoseconds);
            NkDuration(const NkDuration& other);
            
            // Assignment
            NkDuration& operator=(const NkDuration& other);
            
            // Factory methods
            static NkDuration FromNanoseconds(core::int64 nanoseconds);
            static NkDuration FromMicroseconds(core::int64 microseconds);
            static NkDuration FromMicroseconds(core::float64 microseconds);
            static NkDuration FromMilliseconds(core::int64 milliseconds);
            static NkDuration FromMilliseconds(core::float64 milliseconds);
            static NkDuration FromSeconds(core::int64 seconds);
            static NkDuration FromSeconds(core::float64 seconds);
            static NkDuration FromMinutes(core::int64 minutes);
            static NkDuration FromMinutes(core::float64 minutes);
            static NkDuration FromHours(core::int64 hours);
            static NkDuration FromHours(core::float64 hours);
            static NkDuration FromDays(core::int64 days);
            static NkDuration FromDays(core::float64 days);
            
            // Conversion methods
            core::int64 ToNanoseconds() const;
            core::float64 ToMicrosecondsF() const;
            core::int64 ToMicroseconds() const;
            core::float64 ToMillisecondsF() const;
            core::int64 ToMilliseconds() const;
            core::float64 ToSecondsF() const;
            core::int64 ToSeconds() const;
            core::float64 ToMinutesF() const;
            core::int64 ToMinutes() const;
            core::float64 ToHoursF() const;
            core::int64 ToHours() const;
            core::float64 ToDaysF() const;
            core::int64 ToDays() const;
            
            // Arithmetic operations
            NkDuration operator+(const NkDuration& other) const;
            NkDuration operator-(const NkDuration& other) const;
            NkDuration operator*(core::float64 scalar) const;
            NkDuration operator/(core::float64 scalar) const;
            core::float64 operator/(const NkDuration& other) const;
            
            NkDuration& operator+=(const NkDuration& other);
            NkDuration& operator-=(const NkDuration& other);
            NkDuration& operator*=(core::float64 scalar);
            NkDuration& operator/=(core::float64 scalar);
            
            // Unary operators
            NkDuration operator-() const;
            
            // Comparison operators
            bool operator==(const NkDuration& other) const;
            bool operator!=(const NkDuration& other) const;
            bool operator<(const NkDuration& other) const;
            bool operator<=(const NkDuration& other) const;
            bool operator>(const NkDuration& other) const;
            bool operator>=(const NkDuration& other) const;
            
            // Utility methods
            NkDuration Abs() const;
            bool IsNegative() const;
            bool IsZero() const;
            bool IsPositive() const;
            
            // String conversion
            std::string ToString() const;
            std::string ToStringPrecise() const;
            
            // Constants
            static NkDuration Zero();
            static NkDuration Max();
            static NkDuration Min();
    };
    
    // Non-member operators
    NkDuration operator*(core::float64 scalar, const NkDuration& duration);
        
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================