// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\Containers\Views\NkSpan.h
// DESCRIPTION: Span - Non-owning view over contiguous sequence (std::span)
// AUTEUR: Rihen
// DATE: 2026-02-09
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#include "NkSpan.h"

namespace nkentseu {
    namespace entseu {
        // TODO: Ajouter les implémentations ici
    } // namespace entseu
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================