// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\pch\pch.h
// DESCRIPTION: En-tête précompilé pour la compilation
// AUTEUR: Rihen
// DATE: 2026
// -----------------------------------------------------------------------------

#pragma once

// PCH NKCore: headers C/C++ de base uniquement (pas de STL conteneurs)
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================
