// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\Reflection\NkRegistry.cpp
// DESCRIPTION: Implémentation de Système de réflexion
// AUTEUR: Rihen
// DATE: 2026
// -----------------------------------------------------------------------------

#include "NKReflection/NkRegistry.h"

namespace nkentseu {
    
        // Placeholder explicite: implementation a completer; cette unite ne contient pas encore de logique runtime.
    
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================