// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

cbuffer CameraUBO : register(b0)
{
    column_major float4x4 CameraUBO_view;
    column_major float4x4 CameraUBO_proj;
    column_major float4x4 CameraUBO_viewProj;
    column_major float4x4 CameraUBO_invViewProj;
    float4 CameraUBO_camPos;
    float4 CameraUBO_camDir;
    float2 CameraUBO_viewport;
    float CameraUBO_time;
    float CameraUBO_deltaTime;
    float CameraUBO_iblStrength;
};

cbuffer NkGraphParams : register(b8)
{
    float NkGraphParams_usure;
    float NkGraphParams__nkPad0;
    float NkGraphParams__nkPad1;
    float NkGraphParams__nkPad2;
    float3 NkGraphParams_teinte;
};


struct PS_Input
{
    float4 _Position : SV_Position;
    float3 vworldpos : TEXCOORD0;
    float3 vnormal : TEXCOORD1;
    float2 vuv : TEXCOORD2;
    float4 vcolor : TEXCOORD3;
    bool   IsFrontFace : SV_IsFrontFace;
};

struct PS_Output
{
    float4 fragcolor : SV_Target0;
    float4 fragaux : SV_Target1;
};

PS_Output main(PS_Input input)
{
    PS_Output output;
    float3 nkgeomn = normalize(input.vnormal);
    float3 n2_albedo = (float3)(0.0f);
    float n2_metallic = 0.0f;
    float n2_roughness = NkGraphParams_usure;
    float3 n2_emission = NkGraphParams_teinte;
    float3 n2_normal = nkgeomn;
    float3 surfalbedo = n2_albedo;
    float surfmetallic = n2_metallic;
    float surfroughness = n2_roughness;
    float3 surfemission = n2_emission;
    float3 surfnormal = n2_normal;
    float3 n3 = normalize(surfnormal);
    float3 l = normalize(float3(-0.3f, 1.0f, 0.4f));
    float3 v = normalize((CameraUBO_camPos.xyz - input.vworldpos));
    float3 h = normalize((l + v));
    float ndotl = max(dot(n3, l), 0.0f);
    float ndoth = max(dot(n3, h), 0.0f);
    float specexp = lerp(128.0f, 2.0f, surfroughness);
    float spec = pow(ndoth, specexp);
    float3 speccolor = lerp((float3)(1.0f), surfalbedo, surfmetallic);
    float3 diffuse = (surfalbedo * (ndotl + 0.18f));
    float3 specular = ((speccolor * spec) * ((surfmetallic * 0.7f) + 0.3f));
    output.fragcolor = float4(((diffuse + specular) + surfemission), 1.0f);
    output.fragaux = float4(0.0f, 0.0f, 0.0f, 0.0f);
    return output;
}

