// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\String\Encoding\NkASCII.cpp
// DESCRIPTION: ASCII implementation
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#include "NkASCII.h"

namespace nkentseu {
    
        namespace encoding {
            namespace ascii {

                bool NkIsValid(const char* str, usize length) NK_NOEXCEPT {
                    if (!str) return false;
                    
                    for (usize i = 0; i < length; ++i) {
                        if (!NkIsASCII(str[i])) {
                            return false;
                        }
                    }
                    return true;
                }

                int NkCompareIgnoreCase(const char* lhs, const char* rhs, usize length) NK_NOEXCEPT {
                    if (!lhs || !rhs) return lhs == rhs ? 0 : (lhs ? 1 : -1);
                    
                    for (usize i = 0; i < length; ++i) {
                        char l = NkToLower(lhs[i]);
                        char r = NkToLower(rhs[i]);
                        if (l < r) return -1;
                        if (l > r) return 1;
                    }
                    return 0;
                }

                bool NkEqualsIgnoreCase(const char* lhs, const char* rhs, usize length) NK_NOEXCEPT {
                    return NkCompareIgnoreCase(lhs, rhs, length) == 0;
                }

                void NkToUpperInPlace(char* str, usize length) NK_NOEXCEPT {
                    if (!str) return;
                    for (usize i = 0; i < length; ++i) {
                        str[i] = NkToUpper(str[i]);
                    }
                }

                void NkToLowerInPlace(char* str, usize length) NK_NOEXCEPT {
                    if (!str) return;
                    for (usize i = 0; i < length; ++i) {
                        str[i] = NkToLower(str[i]);
                    }
                }

            } // namespace ascii
        } // namespace encoding
    
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================