// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\String\Encoding\NkUTF8.h
// DESCRIPTION: UTF-8 encoding/decoding
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF8_H_INCLUDED
#define NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF8_H_INCLUDED

#include "NkEncoding.h"

namespace nkentseu {
    
        namespace encoding {
            namespace utf8 {
                
                /**
                 * @brief Décode un codepoint UTF-8
                 * @param str Pointeur vers début séquence
                 * @param outCodepoint Codepoint Unicode décodé
                 * @return Nombre de bytes consommés (0 si invalide)
                 */
                NKENTSEU_CORE_API usize NkDecodeChar(const Char* str, uint32& outCodepoint);
                
                /**
                 * @brief Encode un codepoint en UTF-8
                 * @param codepoint Codepoint Unicode
                 * @param outBuffer Buffer destination (min 4 bytes)
                 * @return Nombre de bytes écrits (0 si invalide)
                 */
                NKENTSEU_CORE_API usize NkEncodeChar(uint32 codepoint, Char* outBuffer);
                
                /**
                 * @brief Longueur d'un codepoint UTF-8
                 */
                NKENTSEU_CORE_API usize NkCharLength(Char firstByte);
                NKENTSEU_CORE_API usize NkCodepointLength(uint32 codepoint);
                
                /**
                 * @brief Compte le nombre de caractères (codepoints)
                 */
                NKENTSEU_CORE_API usize NkCountChars(const Char* str, usize byteLength);
                
                /**
                 * @brief Avance au prochain caractère
                 */
                NKENTSEU_CORE_API const Char* NkNextChar(const Char* str);
                
                /**
                 * @brief Recule au caractère précédent
                 */
                NKENTSEU_CORE_API const Char* NkPrevChar(const Char* str, const Char* start);
                
                /**
                 * @brief Vérifie si byte est continuation (10xxxxxx)
                 */
                NKENTSEU_FORCE_INLINE bool NkIsContinuationByte(Char byte) {
                    return (byte & 0xC0) == 0x80;
                }
                
                /**
                 * @brief Vérifie validité UTF-8
                 */
                NKENTSEU_CORE_API bool NkIsValid(const Char* str, usize length);
                NKENTSEU_CORE_API bool NkIsValidCodepoint(uint32 codepoint);
                
                /**
                 * @brief Conversion
                 */
                NKENTSEU_CORE_API NkConversionResult NkToUTF16(const Char* src, usize srcLen, 
                                                uint16* dst, usize dstLen, 
                                                usize& bytesRead, usize& charsWritten);
                
                NKENTSEU_CORE_API NkConversionResult NkToUTF32(const Char* src, usize srcLen,
                                                uint32* dst, usize dstLen,
                                                usize& bytesRead, usize& charsWritten);
                
                /**
                 * @brief Depuis UTF-16/32
                 */
                NKENTSEU_CORE_API NkConversionResult NkFromUTF16(const uint16* src, usize srcLen,
                                                Char* dst, usize dstLen,
                                                usize& charsRead, usize& bytesWritten);
                
                NKENTSEU_CORE_API NkConversionResult NkFromUTF32(const uint32* src, usize srcLen,
                                                Char* dst, usize dstLen,
                                                usize& charsRead, usize& bytesWritten);
                
            } // namespace utf8
        } // namespace encoding
    
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_STRING_ENCODING_NKUTF8_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================