// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\String\Encoding\NkUTF16.h
// DESCRIPTION: UTF-16 encoding/decoding
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF16_H_INCLUDED
#define NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF16_H_INCLUDED

#include "NkEncoding.h"

namespace nkentseu {
    
        namespace encoding {
            namespace utf16 {
                
                /**
                 * @brief Surrogate pairs (U+D800 - U+DFFF)
                 */
                constexpr uint16 NK_HIGH_SURROGATE_START = 0xD800;
                constexpr uint16 NK_HIGH_SURROGATE_END = 0xDBFF;
                constexpr uint16 NK_LOW_SURROGATE_START = 0xDC00;
                constexpr uint16 NK_LOW_SURROGATE_END = 0xDFFF;
                
                /**
                 * @brief Vérifie si surrogate
                 */
                NKENTSEU_FORCE_INLINE bool NkIsHighSurrogate(uint16 ch) {
                    return ch >= NK_HIGH_SURROGATE_START && ch <= NK_HIGH_SURROGATE_END;
                }
                
                NKENTSEU_FORCE_INLINE bool NkIsLowSurrogate(uint16 ch) {
                    return ch >= NK_LOW_SURROGATE_START && ch <= NK_LOW_SURROGATE_END;
                }
                
                NKENTSEU_FORCE_INLINE bool NkIsSurrogate(uint16 ch) {
                    return ch >= NK_HIGH_SURROGATE_START && ch <= NK_LOW_SURROGATE_END;
                }
                
                /**
                 * @brief Décode codepoint UTF-16
                 */
                NKENTSEU_CORE_API usize NkDecodeChar(const uint16* str, uint32& outCodepoint);
                
                /**
                 * @brief Encode codepoint en UTF-16
                 */
                NKENTSEU_CORE_API usize NkEncodeChar(uint32 codepoint, uint16* outBuffer);
                
                /**
                 * @brief Longueur séquence
                 */
                NKENTSEU_CORE_API usize NkCharLength(uint16 firstUnit);
                NKENTSEU_CORE_API usize NkCodepointLength(uint32 codepoint);
                
                /**
                 * @brief Compte caractères
                 */
                NKENTSEU_CORE_API usize NkCountChars(const uint16* str, usize unitLength);
                
                /**
                 * @brief Navigation
                 */
                NKENTSEU_CORE_API const uint16* NkNextChar(const uint16* str);
                NKENTSEU_CORE_API const uint16* NkPrevChar(const uint16* str, const uint16* start);
                
                /**
                 * @brief Validation
                 */
                NKENTSEU_CORE_API bool NkIsValid(const uint16* str, usize length);
                
                /**
                 * @brief Conversions
                 */
                NKENTSEU_CORE_API NkConversionResult NkToUTF8(const uint16* src, usize srcLen,
                                                Char* dst, usize dstLen,
                                                usize& charsRead, usize& bytesWritten);
                
                NKENTSEU_CORE_API NkConversionResult NkToUTF32(const uint16* src, usize srcLen,
                                                uint32* dst, usize dstLen,
                                                usize& charsRead, usize& unitsWritten);
                
            } // namespace utf16
        } // namespace encoding
    
} // namespace nkentseu

#endif // NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF16_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================