// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\String\Encoding\NkUTF32.cpp
// DESCRIPTION: UTF-32 implementation
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#include "NkUTF32.h"
#include "NkUTF8.h"
#include "NkUTF16.h"

namespace nkentseu {
    
        namespace encoding {
            namespace utf32 {

                bool NkIsValid(const uint32* str, usize length) {
                    if (!str) return false;
                    
                    for (usize i = 0; i < length; ++i) {
                        if (!NkIsValidCodepoint(str[i])) {
                            return false;
                        }
                    }
                    return true;
                }

                NkConversionResult NkToUTF8(const uint32* src, usize srcLen, Char* dst, usize dstLen,
                                            usize& charsRead, usize& bytesWritten) {
                    if (!src || !dst) return NkConversionResult::NK_SOURCE_ILLEGAL;
                    
                    charsRead = 0;
                    bytesWritten = 0;
                    
                    while (charsRead < srcLen && bytesWritten < dstLen) {
                        Char buffer[4];
                        usize bytes = utf8::NkEncodeChar(src[charsRead], buffer);
                        
                        if (bytes == 0) return NkConversionResult::NK_SOURCE_ILLEGAL;
                        if (bytesWritten + bytes > dstLen) return NkConversionResult::NK_TARGET_EXHAUSTED;
                        
                        for (usize i = 0; i < bytes; ++i) {
                            dst[bytesWritten++] = buffer[i];
                        }
                        ++charsRead;
                    }
                    
                    return charsRead < srcLen ? NkConversionResult::NK_SOURCE_EXHAUSTED : NkConversionResult::NK_SUCCESS;
                }

                NkConversionResult NkToUTF16(const uint32* src, usize srcLen, uint16* dst, usize dstLen,
                                            usize& charsRead, usize& unitsWritten) {
                    if (!src || !dst) return NkConversionResult::NK_SOURCE_ILLEGAL;
                    
                    charsRead = 0;
                    unitsWritten = 0;
                    
                    while (charsRead < srcLen && unitsWritten < dstLen) {
                        uint16 buffer[2];
                        usize units = utf16::NkEncodeChar(src[charsRead], buffer);
                        
                        if (units == 0) return NkConversionResult::NK_SOURCE_ILLEGAL;
                        if (unitsWritten + units > dstLen) return NkConversionResult::NK_TARGET_EXHAUSTED;
                        
                        for (usize i = 0; i < units; ++i) {
                            dst[unitsWritten++] = buffer[i];
                        }
                        ++charsRead;
                    }
                    
                    return charsRead < srcLen ? NkConversionResult::NK_SOURCE_EXHAUSTED : NkConversionResult::NK_SUCCESS;
                }

            } // namespace utf32
        } // namespace encoding
    
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================