// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\String\Encoding\NkUTF32.h
// DESCRIPTION: UTF-32 encoding/decoding
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF32_H_INCLUDED
#define NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF32_H_INCLUDED

#include "NkEncoding.h"

namespace nkentseu {
    namespace core {
        namespace encoding {
            namespace utf32 {
                
                /**
                 * @brief Codepoint maximum Unicode
                 */
                constexpr uint32 NK_MAX_UNICODE = 0x10FFFF;
                
                /**
                 * @brief Vérifie validité codepoint
                 */
                NKENTSEU_FORCE_INLINE bool NkIsValidCodepoint(uint32 codepoint) {
                    return codepoint <= NK_MAX_UNICODE && 
                        !(codepoint >= 0xD800 && codepoint <= 0xDFFF);  // Pas surrogate
                }
                
                /**
                 * @brief Longueur toujours 1 (1 codepoint = 1 uint32)
                 */
                NKENTSEU_FORCE_INLINE usize NkCharLength(uint32) {
                    return 1;
                }
                
                /**
                 * @brief Compte caractères (= nombre de codepoints)
                 */
                NKENTSEU_FORCE_INLINE usize NkCountChars(const uint32*, usize length) {
                    return length;
                }
                
                /**
                 * @brief Navigation triviale
                 */
                NKENTSEU_FORCE_INLINE const uint32* NkNextChar(const uint32* str) {
                    return str + 1;
                }
                
                NKENTSEU_FORCE_INLINE const uint32* NkPrevChar(const uint32* str, const uint32*) {
                    return str - 1;
                }
                
                /**
                 * @brief Validation
                 */
                NKENTSEU_CORE_API bool NkIsValid(const uint32* str, usize length);
                
                /**
                 * @brief Conversions
                 */
                NKENTSEU_CORE_API NkConversionResult NkToUTF8(const uint32* src, usize srcLen,
                                                char* dst, usize dstLen,
                                                usize& charsRead, usize& bytesWritten);
                
                NKENTSEU_CORE_API NkConversionResult NkToUTF16(const uint32* src, usize srcLen,
                                                uint16* dst, usize dstLen,
                                                usize& charsRead, usize& unitsWritten);
                
            } // namespace utf32
        } // namespace encoding
    } // namespace core
} // namespace nkentseu

#endif // NK_CORE_NKCORE_SRC_NKCORE_STRING_ENCODING_NKUTF32_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================