// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\Assert\NkAssertion.h
// DESCRIPTION: Structure d'assertion
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#pragma once

#ifndef NKENTSEU_CORE_NKCORE_SRC_NKCORE_ASSERT_NKASSERTION_H_INCLUDED
#define NKENTSEU_CORE_NKCORE_SRC_NKCORE_ASSERT_NKASSERTION_H_INCLUDED

#include "NKCore/NkTypes.h"

/**
 * @brief Namespace nkentseu.
 */
namespace nkentseu {
/**
 * @brief Namespace core.
 */
namespace core {

/**
 * @brief Informations sur une assertion échouée
 */
struct NkAssertionInfo {
	const nk_char *expression; ///< Expression qui a échoué
	const nk_char *message;	   ///< Message custom
	const nk_char *file;	   ///< Fichier source
	nk_int32 line;			   ///< Ligne source
	const nk_char *function;   ///< Nom de la fonction
};

/**
 * @brief Action à prendre lors d'une assertion échouée
 */
enum class NkAssertAction {
	NK_CONTINUE,  // Continue execution
	NK_BREAK,	  // Break into debugger
	NK_ABORT,	  // Abort program
	NK_IGNORE,	  // Ignore this assertion from now on
	NK_IGNORE_ALL ///< Ignorer toutes
};

} // namespace core
} // namespace nkentseu

#endif

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================