// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\Assert\NkAssertHandler.h
// DESCRIPTION: Gestionnaire d'assertions
// AUTEUR: Rihen
// DATE: 2026-02-07
// -----------------------------------------------------------------------------

#pragma once

#ifndef NKENTSEU_CORE_NKCORE_SRC_NKCORE_ASSERT_NKASSERTHANDLER_H_INCLUDED
#define NKENTSEU_CORE_NKCORE_SRC_NKCORE_ASSERT_NKASSERTHANDLER_H_INCLUDED

#include "NkAssertion.h"
#include "NKCore/NkCoreExport.h"
#include "NKCore/NkTypes.h"

/**
 * @brief Namespace nkentseu.
 */
namespace nkentseu {
	/**
	 * @brief Namespace core.
	 */
	namespace core {

		/**
		 * @brief Type de callback pour assertions
		 */
		using NkAssertCallback = NkAssertAction (*)(const NkAssertionInfo &);

		/**
		 * @brief Gestionnaire global d'assertions
		 */
		class NKENTSEU_CORE_API NkAssertHandler {
			public:
				/**
				 * @brief Récupère callback actuel
				 */
				static NkAssertCallback GetCallback();

				/**
				 * @brief Définit callback custom
				 */
				static void SetCallback(NkAssertCallback callback);

				/**
				 * @brief Callback par défaut
				 */
				static NkAssertAction DefaultCallback(const NkAssertionInfo &info);

				/**
				 * @brief Gère une assertion échouée
				 */
				static NkAssertAction HandleAssertion(const NkAssertionInfo &info);
		};

	} // namespace core
} // namespace nkentseu

#endif

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================